
#schema-all.sql

server:
  port: 5656
spring:
  batch:
    job:
      name: csv-reader
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:h2:mem:testDB
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
